services:
  localstack:
    image: localstack/localstack:latest
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    ports:
      - "4566:4566"   # LocalStack edge port (API Gateway, Lambda, S3, etc.)
      - "4510-4559:4510-4559"
    environment:
      SERVICES: "lambda,apigateway,s3,dynamodb,iam"
      DEBUG: 0
      LAMBDA_EXECUTOR: "docker-reuse"
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL}
      AWS_EXTERNAL_ENDPOINT_URL: ${AWS_EXTERNAL_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET: ${S3_BUCKET} 
      DYNAMODB_TABLE: ${DYNAMODB_TABLE}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      # auto init scripts
      - "./init:/etc/localstack/init/ready.d"
      - "./:/project"
